language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="aws:. aws-lwt:. aws-async:."
  # - DEPOPTS="github-unix"
  matrix:
  - PACKAGE="aws"       DISTRO="ubuntu-18.04" OCAML_VERSION="4.04"
  - PACKAGE="aws-lwt"   DISTRO="ubuntu-18.04" OCAML_VERSION="4.04"
  - PACKAGE="aws-async" DISTRO="ubuntu-18.04" OCAML_VERSION="4.04"
  # - PACKAGE="aws_gen"   DISTRO="ubuntu-18.04" OCAML_VERSION="4.04"

os:
  - linux
